package com.infoshareacademy.domain;

public enum Category {

    KRYMINAL_SENSACJA_THRILLER,
    LITERATURA_PIEKNA,
    HISTORYCZNA,
    FANTASTYKA_SCIENCE_FICTION,
    PUBLICYSTYKA_BIOGRAFIA,
    OBYCZAJOWA_ROMANS
}
